version: '2'

services:
  # java-agent:
  #   image: appdynamics/java-agent:20.5.0

  mongo-sessions:
    image: mongo
    container_name: mongo-sessions
    hostname: mongo-sessions
    expose: 
      - 27017
  mongo-accounts:
    image: mongo
    container_name: mongo-accounts
    hostname: mongo-accounts
    expose: 
      - 27017
  web-api:
    image: appd_lambda_lab_nodejs_services:latest
    hostname: web-api
    container_name: web-api
    volumes:
      - './graph.json:/graph.json'
    environment: 
      - GRAPH_FILE=/graph.json
      - DEBUG_LEVEL=debug
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    ports:
      - '3000:3000'
  core-services:
    image: appd_lambda_lab_java_services:latest
    hostname: core-services
    container_name: core-services
    volumes:
      - './graph.json:/graph.json'
    environment: 
      - GRAPH_FILE=/graph.json
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}  
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    ports:
      - '8080:8080'
  load:
    container_name: load
    build: 
      context: ./load_container
    volumes:
      - './load.sh:/load.sh'


# volumes:
#   java-agent: